ALTER TABLE public.media
  ADD COLUMN IF NOT EXISTS alt_text text DEFAULT '' NOT NULL,
  ADD COLUMN IF NOT EXISTS title text DEFAULT '' NOT NULL,
  ADD COLUMN IF NOT EXISTS caption text DEFAULT '' NOT NULL,
  ADD COLUMN IF NOT EXISTS description text DEFAULT '' NOT NULL;